# Generated by Django 4.1.2 on 2023-01-21 16:54

import Project.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PC", "Pc"),
                            ("TABLET", "Tablet"),
                            ("MOBILE", "Mobile"),
                            ("OTHER", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        upload_to=Project.storage.image_file_upload,
                        verbose_name="Image",
                    ),
                ),
            ],
        ),
    ]
