# Generated by Django 4.1.9 on 2023-08-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_type",
            field=models.CharField(
                choices=[("CARD", "Card"), ("OTHER", "Other")], max_length=100
            ),
        ),
    ]
