# Generated by Django 4.1.9 on 2023-08-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Images", "0001_initial"),
        ("Users", "0002_user_groups_user_user_permissions_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="images",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_networks",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="Images.image",
            ),
        ),
    ]
