# Generated by Django 4.1.2 on 2023-02-08 21:58

import Project.storage
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "tags",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=20),
                        max_length=400,
                        null=True,
                        size=10,
                    ),
                ),
                ("url", models.URLField(null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=Project.storage.document_file_upload,
                        verbose_name="File",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Images.image",
                    ),
                ),
            ],
        ),
    ]
