# Generated by Django 4.1.2 on 2023-01-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("LINKEDIN", "Linkedin"),
                            ("GITHUB", "Github"),
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("TWITTER", "Twitter"),
                            ("TIKTOK", "Tiktok"),
                        ],
                        max_length=100,
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
    ]
